### ISSUE TITLE
Atto don't like multilang2

### ISSUE THREAD

**Issue by sberger** [KepaUrzelai/moodle-atto_multilang2#5]
If multilang2 is activated in the settings of the Atto editor (toolbar config editor_atto | toolbar -> multilang2 = multilang2), certain javascript-based actions will no longer work, such as the drag & drop area for file upload or drop-down menus (tested in moodle 3.8).
This happens even if the filter itself is disabled. The reason seems to be the inclusion in the Atto toolbar.
Installed versions are:
* Multi-Language Content (v2) filter_multilang2 | 1.1.1 | 2019111900
* Multi-Language Content (v2) atto_multilang2 | master - Release v1.11.2 (Build 2019112700) for Moodle 3.6, 3.7 and 3.8 | 2019112700
* Moodle 3.8 (Build: 20191118)

![with_multilang2_in_atto](https://user-images.githubusercontent.com/3737740/70221903-6e5f1d00-1749-11ea-994a-c1d6b192d277.png)

![without_multilang2_in_atto](https://user-images.githubusercontent.com/3737740/70221905-6ef7b380-1749-11ea-93a4-394e601f7c36.png)

**Comment by lucaboesch** [comment]
Thanks for the report, Stefanie!
Luckily I don't have this in my Moodle 3.6.7…!
The steps to reproduce as above are: Enable editing mod in your course, then 'Add an activity or resource' of type 'File', right?

I've got the button included not as multilang=multilang but in line with other. And in a different order probably. Would you mind trying that out on your site?

```
collapse = collapse
style1 = title,bold,italic,bfhfontcolor,bfhbackcolor
list = unorderedlist,orderedlist
links = link
files = image, media, recordrtc, managefiles
style2 = underline,strike,subscript,superscript
align = align
indent = indent
insert = equation,charmap,table,clear,emoticon,embedquestion
undo = undo
accessibility = accessibilitychecker,accessibilityhelper
other = html,multilang2,fullscreen,cloze,kalturamedia
```
Best,
Luca

**Comment by sberger** [comment]
> The steps to reproduce as above are: Enable editing mode in your course, then 'Add an activity or resource' of type 'File',  right?
Yes, it was the way ...

And I'm sorry, it's the same with:
`....
insert = equation, charmap, table, emoticon
undo = undo
accessibility = accessibilitychecker, accessibilityhelper
other = rtl, multilang2`

Even the menu of the Atto-Mutilang2 filter can no longer be closed.

![Bildschirmfoto 2019-12-05 um 11 26 03](https://user-images.githubusercontent.com/3737740/70227403-d0705000-1752-11ea-99d9-e52f671b159a.png)

**Comment by izendegi** [comment]
Hi there,

I haven't been able to reproduce this issue either, but it seems like it's related to some old issues that were fixed [here](https://github.com/julenpardo/moodle-atto_multilang2/issues/18#issuecomment-335013278).

@sberger , can you tell us if you're using some other non-standard plugins (atto plugins, theme...) on that site that come into conflict with atto_multilang2?

**Comment by sberger** [comment]
yes, of course, it's my test moodle :-)
Here is the list of additional plugins:

![Visioex – Moodle 3 8_ Administration_ Plugins_ Plugins overview](https://user-images.githubusercontent.com/3737740/70234797-bab65700-1761-11ea-9625-0556c34645bb.png)

**Comment by KepaUrzelai** [comment]
Hi everyone, 

I have reproduced the issue adding the HTMLPlus plugin to my Moodle version 3.8 instance, so this is the one causing conflict with the Atto Multilang2 plugin. 
The solution in this case is very easy because, since Moodle version 3.6, this plugin is standardized. This is to say that the functionalities of atto_htmplus plugin were incorporated into atto_html (see [MDL-5177](https://tracker.moodle.org/browse/MDL-51177)), so you just need to delete that first one.

I hope it helps.

**Comment by sberger** [comment]
You are right, without HTML+ the Multilang2 filter works without problems. Thank a lot!
Stefanie
