### ISSUE TITLE
3.10 - Plugin prevents other key core functionality from working

### ISSUE THREAD

**Issue by eddyc123** [KepaUrzelai/moodle-atto_multilang2#6]
This plugins seems to prevent multiple actions from occurring in the platform when it is installed. For example:

- HTML editor cannot be viewed in the atto editor (nothing happens upon clicking the atto toolbar button)
![image](https://user-images.githubusercontent.com/77615237/104904528-2618b380-5979-11eb-9ea0-fd0d83f1e56f.png)

- Some buttons simply do not work when trying to add files, for example in a label when trying to use "Browse repositories" (nothing happens when this plugin this installed).
![image](https://user-images.githubusercontent.com/77615237/104904575-36309300-5979-11eb-8c0b-1f77b68693f3.png)

- Files do not loads in "upload" areas as it presents you with a spinning loading icon and never loads. This means there are certain areas you can never upload images too..... For example in the course settings area, for the course header image.
![image](https://user-images.githubusercontent.com/77615237/104904792-80b20f80-5979-11eb-9e37-f9fedbdceca9.png)

**N.B.** This occurs using any theme and was tested in Boost theme format (as initially this involved a custom theme).

Unfortunately this makes the plugin unusable as it restricts other core/standard required functionality.

**Comment by eddyc123** [comment]
I have not pasted any browser errors here as I am not a programmer and would likely paste the wrong part. It is however, easy to replicate this issue (e.g. in Moodle 3.10 in Boost theme).

**Comment by KepaUrzelai** [comment]
Hello @eddyc123,

I could not reproduce this issue, make sure you are using the latest version of the plugin ([compatible with Moodle v3.10](https://moodle.org/plugins/pluginversions.php?plugin=atto_multilang2)).

Also, it is known that the plugin does weird things with the old [HTML+ plugin](https://moodle.org/plugins/atto_htmlplus), whose newest version is core now and works like a charm with atto_multilang2. Please, check if your site is still using the old one:

1. Navigate to Site administration -> Plugins -> Text editors -> Atto HTML editor -> Atto toolbar settings
2. Replace any occurrence of the _htmlplus_ plugin with _html_.



A greeting,
Kepa

**Comment by eddyc123** [comment]
I appreciate the fast response! You are very much correct, it's that HTML+ plugin for the atto edit.... That pesky plugin caused mayhem! :) Thanks for the point in that direction, this would have caused mayhem on a few platforms.
Thanks again!
