### ISSUE TITLE
Unit test failure: Privacy provider

### ISSUE THREAD

**Issue by mattporritt** [KepaUrzelai/moodle-atto_multilang2#7]
The core Moodle unit test suite was failing in Moodle 3.9.

The test that was failing is:
`vendor/bin/phpunit --stop-on-failure "provider_testcase" privacy/tests/provider_test.php`

This is to do with an inccorect implementation of the Null Provider in the Privacy API.  The correct way is outlined here: https://docs.moodle.org/dev/Privacy_API#Example

A patch that fixes this issue is:
```
diff --git a/classes/privacy/provider.php b/classes/privacy/provider.php
index 42c59c7..c8d50f6 100644
--- a/classes/privacy/provider.php
+++ b/classes/privacy/provider.php
@@ -43,6 +43,6 @@ class provider implements
      * @return  string
      */
     public static function get_reason() : string {
-        return get_string('privacy:metadata', 'atto_multilang2');
+        return 'privacy:metadata';
     }
 }
```

**Comment by KepaUrzelai** [comment]
Hi @mattporritt,

Thank you for reporting this.
You are right, I will apply the patch and release a new plugin version.

Kepa
