### ISSUE TITLE
Make a moodle-tiny_multilang2

### ISSUE THREAD

**Issue by lucaboesch** [KepaUrzelai/moodle-atto_multilang2#9]
It would be worthwhile to create the multilang2 editor plugin for the new Tiny editor in Moodle.

**Comment by KepaUrzelai** [comment]
Hello @lucaboesch,

You're right, we have also think about it recently, and there is an old plugin ([tinymce_moodlelang2](https://github.com/iarenaza/moodle-tinymce_moodlelang2)) that we could use as a starting point, but sadly I can tell you when we'll start with it (it will be sooner or later).

Noted your request, I'll close this issue.

__
Thank you.
